export enum Role {
  ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  ROLE_ADMIN_MANAGER = 'ROLE_ADMIN_MANAGER',
  ROLE_STAFF = 'ROLE_STAFF',
  ROLE_USER = 'ROLE_USER',
  ROLE_MINDBODY_USER = 'ROLE_MINDBODY_USER'
}
